// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'

    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBj50yHwfv7X3CCq_bgt9PmMXIX_Cl4RsA',
    appId: '1:774153958132:web:2c7d7b0dd6d937327324a1',
    messagingSenderId: '774153958132',
    projectId: 'otimobapps25',
    authDomain: 'otimobapps25.firebaseapp.com',
    storageBucket: 'otimobapps25.firebasestorage.app',
    measurementId: 'G-YVTZT18N9J',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCn_W-JpLaPWNEDM6VRMPyBM2i-U9ttka0',
    appId: '1:774153958132:android:e920cf878e5369d77324a1',
    messagingSenderId: '774153958132',
    projectId: 'otimobapps25',
    storageBucket: 'otimobapps25.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBj50yHwfv7X3CCq_bgt9PmMXIX_Cl4RsA',
    appId: '1:774153958132:web:92a07227220658c77324a1',
    messagingSenderId: '774153958132',
    projectId: 'otimobapps25',
    authDomain: 'otimobapps25.firebaseapp.com',
    storageBucket: 'otimobapps25.firebasestorage.app',
    measurementId: 'G-GSDX6WK1DP',
  );
}